Replace sprintf with snprintf in unpack
Fixes errors compiling on mac with a newer xcode level.

/Users/jenkins/workspace/Build_JDK11_aarch64_mac_Personal/src/jdk.pack/share/native/common-unpack/unpack.h:421:52:
error: 'sprintf' is deprecated: This function is provided for
compatibility reasons only.  Due to security concerns inherent in the
design of sprintf(3), it is highly recommended that you use snprintf(3)
instead. [-Werror,-Wdeprecated-declarations]

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>